export type SvgElement={tag:'path'|'line'|'circle'|'text'|'image';attrs:Record<string,string|number>}
export type FlatOptions={bodyWidth?:number;bodyLength?:number;sleeveLength?:number;measurements?:{code:string;name:string;value?:number;unit?:string;tolerance?:number;anchor?:string;direction?:'horizontal'|'vertical'|'curved'}[]}
export type ArtworkOverlay={id?:string;name:string;technique:string;placement:string;width:string;height:string;colors:string;notes?:string;assetDataUrl?:string}
const path=(d:string,attrs:Record<string,string|number>={}):SvgElement=>({tag:'path',attrs:{d,fill:'none',stroke:'#111','stroke-width':1.8,'stroke-linejoin':'round',...attrs}})
const line=(x1:number,y1:number,x2:number,y2:number,attrs:Record<string,string|number>={}):SvgElement=>({tag:'line',attrs:{x1,y1,x2,y2,stroke:'#111','stroke-width':1.4,...attrs}})
const text=(x:number,y:number,value:string,attrs:Record<string,string|number>={}):SvgElement=>({tag:'text',attrs:{x,y,'font-family':'Arial, sans-serif','font-size':9,fill:'#111',...attrs,'data-text':value}})
function dimension(x1:number,y1:number,x2:number,y2:number,label:string,offset=14):SvgElement[]{const horizontal=y1===y2,ox=horizontal?0:offset,oy=horizontal?offset:0;return[line(x1,y1,x2,y2,{'stroke-dasharray':'3 3','stroke-width':1}),line(x1,y1,x1+ox,y1+oy,{'stroke-width':.8}),line(x2,y2,x2+ox,y2+oy,{'stroke-width':.8}),text((x1+x2)/2+ox,(y1+y2)/2+oy-3,label,{'text-anchor':'middle','font-size':8})]}
function position(p:string,cx:number,left:number,right:number,top:number,hem:number){switch(p){case'center-front':return{x:cx,y:top+112,w:76,h:50};case'left-chest':return{x:left+28,y:top+58,w:34,h:24};case'right-chest':return{x:right-28,y:top+58,w:34,h:24};case'center-back':return{x:cx,y:top+118,w:76,h:50};case'left-sleeve':return{x:left-34,y:top+74,w:30,h:22};case'right-sleeve':return{x:right+34,y:top+74,w:30,h:22};case'neck-label':return{x:cx,y:top+30,w:28,h:14};case'hem-label':return{x:cx,y:hem-18,w:28,h:14};default:return{x:cx,y:top+112,w:76,h:50}}}
function overlays(artworks:ArtworkOverlay[]|undefined,cx:number,left:number,right:number,top:number,hem:number):SvgElement[]{return(artworks??[]).flatMap((a,i):SvgElement[]=>{const q=position(a.placement,cx,left,right,top,hem),n=String(i+1).padStart(2,'0');const marker=path(`M ${q.x-q.w/2} ${q.y-q.h/2} L ${q.x+q.w/2} ${q.y-q.h/2} L ${q.x+q.w/2} ${q.y+q.h/2} L ${q.x-q.w/2} ${q.y+q.h/2} Z`,{'stroke-dasharray':'3 3','stroke-width':1.1});const callout=text(q.x,q.y+q.h/2+12,`${n} · ${a.name} · ${a.width} × ${a.height}`,{'text-anchor':'middle','font-size':5});const meta=text(q.x,q.y+q.h/2+19,`${a.technique.toUpperCase()} · ${a.placement.replace(/-/g,' ').toUpperCase()}${a.colors?` · ${a.colors}`:''}`,{'text-anchor':'middle','font-size':4.5});if(a.assetDataUrl)return[{tag:'image',attrs:{href:a.assetDataUrl,x:q.x-q.w/2,y:q.y-q.h/2,width:q.w,height:q.h,preserveAspectRatio:'xMidYMid meet',opacity:.82}},marker,callout,meta];return[marker,text(q.x,q.y-2,a.name,{'text-anchor':'middle','font-size':6,'font-weight':'700'}),text(q.x,q.y+7,a.technique.toUpperCase(),{'text-anchor':'middle','font-size':5}),callout,meta]})}
function pomCallouts(measurements:FlatOptions['measurements'],left:number,right:number,top:number,hem:number,cx:number):SvgElement[]{return(measurements??[]).flatMap((m,i)=>{if(m.value==null)return[];const label=`${m.code} · ${m.value}${m.unit??'cm'}${m.tolerance!=null?` ±${m.tolerance}`:''}`;if(m.direction==='horizontal'){const y=top+82+i*12;return[...dimension(left,y,right,y,label,8)]}if(m.direction==='curved'){return[text(cx,top+45+i*11,label,{'text-anchor':'middle','font-size':6})]}const x=right+28+i*11;return[...dimension(x,top,x,hem,label,10)]})}
function garment(category:'tshirt'|'hoodie',o:FlatOptions={},artworks:ArtworkOverlay[]=[]):SvgElement[]{const hoodie=category==='hoodie',w=o.bodyWidth??(hoodie?100:92),h=o.bodyLength??(hoodie?230:220),s=o.sleeveLength??(hoodie?70:52),cx=150,top=hoodie?82:72,left=cx-w/2,right=cx+w/2,hem=top+h;const shape=hoodie?path(`M ${left+22} ${top+18} L ${cx-28} ${top} L ${cx-20} ${top+42} L ${cx} ${top+58} L ${cx+20} ${top+42} L ${cx+28} ${top} L ${right-22} ${top+18} L ${right+s} ${top+72} L ${right+20} ${top+94} L ${right} ${top+64} L ${right} ${hem} L ${left} ${hem} L ${left} ${top+64} L ${left-20} ${top+94} L ${left-s} ${top+72} L ${left-22} ${top+18} Z`):path(`M ${left+22} ${top+18} L ${cx-20} ${top} L ${cx} ${top+18} L ${cx+20} ${top} L ${right-22} ${top+18} L ${right+s} ${top+65} L ${right+22} ${top+85} L ${right} ${top+62} L ${right} ${hem} L ${left} ${hem} L ${left} ${top+62} L ${left-22} ${top+85} L ${left-s} ${top+65} L ${left-22} ${top+18} Z`);return[shape,...(hoodie?[path(`M ${cx-28} ${top} C ${cx-34} ${top-34}, ${cx+34} ${top-34}, ${cx+28} ${top}`),path(`M ${cx-32} ${top+35} C ${cx-16} ${top+62}, ${cx+16} ${top+62}, ${cx+32} ${top+35}`),path(`M ${cx-34} ${top+118} L ${cx+34} ${top+118} L ${cx+28} ${top+158} L ${cx-28} ${top+158} Z`)]:[path(`M ${cx-20} ${top} C ${cx-17} ${top+25}, ${cx+17} ${top+25}, ${cx+20} ${top}`)]),line(left,hem,right,hem,{'stroke-width':2.4}),...dimension(left,hem,right,hem,`${w} cm`,12),...dimension(right,top+64,right,hem,`${h} cm`,22),...pomCallouts(o.measurements,left,right,top,hem,cx),...overlays(artworks,cx,left,right,top,hem),text(cx,hem+38,'FRONT',{'text-anchor':'middle','font-size':10,'font-weight':'700'})]}
export function renderTshirtFlat(o:FlatOptions={},artworks:ArtworkOverlay[]=[]):SvgElement[]{return garment('tshirt',o,artworks)}
export function renderHoodieFlat(o:FlatOptions={},artworks:ArtworkOverlay[]=[]):SvgElement[]{return garment('hoodie',o,artworks)}
export function renderBackFlat(category:'tshirt'|'hoodie',o:FlatOptions={},artworks:ArtworkOverlay[]=[]):SvgElement[]{const all=garment(category,o,artworks);return all.map(e=>e.tag==='text'&&e.attrs['data-text']==='FRONT'?text(Number(e.attrs.x),Number(e.attrs.y),'BACK',{'text-anchor':'middle','font-size':10,'font-weight':'700'}):e)}
export function elementsToSvg(elements:SvgElement[],width=360,height=360):string{const body=elements.map(({tag,attrs})=>{const a={...attrs},value=a['data-text'];delete a['data-text'];const serialized=Object.entries(a).map(([k,v])=>`${k}="${String(v).replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"`).join(' ');return tag==='text'?`<text ${serialized}>${value??''}</text>`:`<${tag} ${serialized} />`}).join('');return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}"><rect width="100%" height="100%" fill="white"/>${body}</svg>`}
export function renderTechnicalFlat(category:'tshirt'|'hoodie',o?:FlatOptions,artworks:ArtworkOverlay[]=[]):string{return elementsToSvg(category==='hoodie'?renderHoodieFlat(o,artworks):renderTshirtFlat(o,artworks))}
