import type { GarmentSpec } from './garment-spec'
import { hoodiePOMs, tshirtPOMs } from './pom'
import { hoodieBOM, tshirtBOM } from './bom'
import { hoodieConstruction, tshirtConstruction } from './construction'
import { renderHoodieFlat, renderTshirtFlat, renderBackFlat, elementsToSvg } from '../engines/technical-flat/svg'
import { createTechPackDocument, renderTechPackSvg } from './tech-pack'
import type { ArtworkSpec } from './artwork'

function valueFor(spec:GarmentSpec,id:string,fallback:number){return spec.measurements.find(item=>item.id===id)?.value??fallback}
function geometryFor(spec:GarmentSpec){return{bodyWidth:valueFor(spec,'chest',spec.category==='hoodie'?100:92),bodyLength:valueFor(spec,'body-length',spec.category==='hoodie'?230:220),sleeveLength:valueFor(spec,'sleeve',spec.category==='hoodie'?70:52)}}
export function buildTechPackPreview(spec:GarmentSpec,artworks:ArtworkSpec[]=[]){const isHoodie=spec.category==='hoodie',poms=isHoodie?hoodiePOMs:tshirtPOMs,bom=isHoodie?hoodieBOM:tshirtBOM,construction=isHoodie?hoodieConstruction:tshirtConstruction,geometry=geometryFor(spec);const overlays=artworks.map(artwork=>({name:artwork.name,technique:artwork.technique,placement:artwork.placement,width:artwork.width,height:artwork.height,colors:artwork.colors,assetDataUrl:artwork.assetDataUrl}));const frontElements=overlays.reduce((elements,overlay)=>isHoodie?renderHoodieFlat(geometry,overlay):renderTshirtFlat(geometry,overlay),isHoodie?renderHoodieFlat(geometry):renderTshirtFlat(geometry));const backArtworks=overlays.filter(a=>a.placement==='center-back');const backElements=backArtworks.length?renderBackFlat(spec.category,geometry,backArtworks[0]):renderBackFlat(spec.category,geometry);const flatSvg=elementsToSvg([...frontElements,...backElements.map(e=>({...e,attrs:{...e.attrs,transform:`translate(190 0) ${e.attrs.transform??''}`}}))]);const document=createTechPackDocument(spec.category);document.styleName=spec.name;document.sections=document.sections.map(section=>section.title==='MEASUREMENTS'?{...section,items:poms.map(p=>`${p.code}: ${p.name} — ${spec.measurements.find(m=>m.id===p.id)?.value??'TBD'} ${p.unit}`)}:section.title==='ARTWORK'?{...section,items:overlays.length?overlays.flatMap(a=>[`${a.name} · ${a.technique}`,`${a.placement} · ${a.width} × ${a.height}`,a.colors]):['No artwork specified']}:section);return{spec,artworks,pom:poms.map(item=>({...item,value:spec.measurements.find(m=>m.id===item.id)?.value??item.value})),bom,construction,flatSvg,sheetSvg:renderTechPackSvg(document,flatSvg)}}
