import { useState } from 'react'
import type { AuthSession } from './auth'
import { renameProject } from './auth'

export interface ProjectMetadata { name:string; reference:string; category:'tshirt'|'hoodie'; fit:'regular'|'oversized'|'cropped'; colorway:string }

export function ProjectMetadataModal({session,projectId,initial,onClose,onSaved}:{session:AuthSession;projectId:string;initial:ProjectMetadata;onClose:()=>void;onSaved:(metadata:ProjectMetadata)=>void}){
 const [metadata,setMetadata]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const save=async()=>{const name=metadata.name.trim();if(!name){setError('Project name is required.');return}setBusy(true);setError('');try{await renameProject(session,projectId,name);onSaved({...metadata,name})}catch(e){setError(e instanceof Error?e.message:'Could not save project metadata')}finally{setBusy(false)}}
 return <div className="modal" onClick={onClose}><div className="project-edit-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><span>EDIT TECH PACK</span><button onClick={onClose}>Close</button></div><div className="project-edit-grid"><label>Project name<input value={metadata.name} onChange={e=>setMetadata({...metadata,name:e.target.value})} autoFocus/></label><label>Style / internal reference<input value={metadata.reference} onChange={e=>setMetadata({...metadata,reference:e.target.value})} placeholder="SS26-TEE-001"/></label><label>Category<select value={metadata.category} onChange={e=>setMetadata({...metadata,category:e.target.value as ProjectMetadata['category']})}><option value="tshirt">T-shirt</option><option value="hoodie">Hoodie</option></select></label><label>Fit<select value={metadata.fit} onChange={e=>setMetadata({...metadata,fit:e.target.value as ProjectMetadata['fit']})}><option value="regular">Regular</option><option value="oversized">Oversized</option><option value="cropped">Cropped</option></select></label><label className="wide">Colorway<input value={metadata.colorway} onChange={e=>setMetadata({...metadata,colorway:e.target.value})} placeholder="Washed Black"/></label></div>{error&&<div className="validation-warning">{error}</div>}<div className="project-edit-actions"><button onClick={onClose}>Cancel</button><button className="export" disabled={busy} onClick={save}>{busy?'Saving…':'Save changes'}</button></div></div></div>
}
