import { StrictMode, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import { createTshirt } from './garments/tshirt'
import { createHoodie } from './garments/hoodie'
import { validateTechPack } from './core/validation'
import { buildTechPackPreview } from './core/build-preview'
import type { ArtworkSpec, ArtworkTechnique, ArtworkPlacement } from './core/artwork'
import { defaultArtwork, artworkPlacementLabels } from './core/artwork'

type Tab='flat'|'measurements'|'bom'|'construction'|'artwork'
type Fit='regular'|'oversized'|'cropped'
type BomEdits=Record<string,{specification?:string;placement?:string}>
type ConstructionEdits=Record<string,{operation?:string;seam?:string;stitch?:string}>
type SavedState={category:'tshirt'|'hoodie';measurements:Record<string,number>;bomEdits:BomEdits;constructionEdits:ConstructionEdits;styleName:string;fit:Fit;colorway:string;artworks:ArtworkSpec[]}
const STORAGE_KEY='tech-pack-studio:v1'
const blankState:SavedState={category:'tshirt',measurements:{},bomEdits:{},constructionEdits:{},styleName:'',fit:'regular',colorway:'',artworks:[{...defaultArtwork}]}
function loadState():SavedState{try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return blankState;const parsed=JSON.parse(raw) as Partial<SavedState>;return {...blankState,...parsed,artworks:Array.isArray(parsed.artworks)&&parsed.artworks.length?parsed.artworks:blankState.artworks}}catch{return blankState}}
function slug(value:string){return(value||'tech-pack').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'tech-pack'}

function App(){
 const saved=useMemo(loadState,[])
 const [category,setCategory]=useState<'tshirt'|'hoodie'>(saved.category),[tab,setTab]=useState<Tab>('flat'),[showSheet,setShowSheet]=useState(false),[showValidation,setShowValidation]=useState(false),[measurements,setMeasurements]=useState<Record<string,number>>(saved.measurements),[bomEdits,setBomEdits]=useState<BomEdits>(saved.bomEdits),[constructionEdits,setConstructionEdits]=useState<ConstructionEdits>(saved.constructionEdits),[styleName,setStyleName]=useState(saved.styleName),[fit,setFit]=useState<Fit>(saved.fit),[colorway,setColorway]=useState(saved.colorway),[artworks,setArtworks]=useState<ArtworkSpec[]>(saved.artworks),[saveState,setSaveState]=useState<'saved'|'saving'|'error'>('saved')
 const spec=useMemo(()=>{const base=category==='tshirt'?createTshirt():createHoodie();base.measurements=base.measurements.map(m=>({...m,value:measurements[m.id]??m.value}));base.fit=fit;if(styleName)base.name=styleName;if(colorway)base.colorways=[colorway];return base},[category,measurements,styleName,fit,colorway])
 const editedBom=useMemo(()=>{const base=category==='tshirt'?createTshirt():createHoodie();return base.bom.map(item=>({...item,...bomEdits[item.id]}))},[category,bomEdits])
 const editedConstruction=useMemo(()=>{const base=category==='tshirt'?createTshirt():createHoodie();return base.construction.map(item=>({...item,...constructionEdits[item.id]}))},[category,constructionEdits])
 const preview=useMemo(()=>buildTechPackPreview(spec,artworks,{bom:editedBom,construction:editedConstruction}),[spec,artworks,editedBom,editedConstruction])
 const validation=validateTechPack(spec,preview.pom,preview.bom,preview.construction,artworks)
 const hasCriticalErrors=validation.errors.length>0
 useEffect(()=>{setSaveState('saving');const timer=window.setTimeout(()=>{try{const state:SavedState={category,measurements,bomEdits,constructionEdits,styleName,fit,colorway,artworks};localStorage.setItem(STORAGE_KEY,JSON.stringify(state));setSaveState('saved')}catch{setSaveState('error')}},350);return()=>window.clearTimeout(timer)},[category,measurements,bomEdits,constructionEdits,styleName,fit,colorway,artworks])
 const updateArtwork=<K extends keyof ArtworkSpec>(id:string,field:K,value:ArtworkSpec[K])=>setArtworks(items=>items.map(item=>item.id===id?{...item,[field]:value}:item))
 const importArtwork=(id:string,file:File)=>{if(!file.type.startsWith('image/'))return;const reader=new FileReader();reader.onload=()=>setArtworks(items=>items.map(item=>item.id===id?{...item,assetName:file.name,assetDataUrl:String(reader.result),name:item.name===defaultArtwork.name?file.name.replace(/\.[^.]+$/,''):item.name}:item));reader.readAsDataURL(file)}
 const addArtwork=()=>setArtworks(items=>[...items,{...defaultArtwork,id:`artwork-${Date.now()}`,name:`Artwork ${items.length+1}`,placement:items.some(a=>a.placement==='center-front')?'center-back':'center-front'}])
 const removeArtwork=(id:string)=>setArtworks(items=>items.length===1?items:items.filter(item=>item.id!==id))
 const newPack=()=>{if(!window.confirm('Start a new tech pack? Unsaved changes are replaced.'))return;setCategory('tshirt');setMeasurements({});setBomEdits({});setConstructionEdits({});setStyleName('');setFit('regular');setColorway('');setArtworks([{...defaultArtwork,id:'artwork-1'}]);setTab('flat');setShowValidation(false)}
 const exportPack=()=>{if(hasCriticalErrors){setShowValidation(true);return}downloadSvg(preview.sheetSvg,`${slug(spec.name)}.svg`)}
 const printPack=()=>{if(hasCriticalErrors){setShowValidation(true);return}openPrintWindow(preview.sheetSvg,spec.name)}
 const validationTab=(error:string):Tab=>error.toLowerCase().includes('artwork')?'artwork':error.toLowerCase().includes('bom')||error.toLowerCase().includes('fabric')?'bom':error.toLowerCase().includes('construction')?'construction':error.toLowerCase().includes('measurement')?'measurements':'flat'
 const tabs:Tab[]=['flat','measurements','bom','construction','artwork']
 return <main className="app">
  <header className="topbar"><div className="brand">TECH PACK <span>STUDIO</span></div><div className="top-actions"><span className={validation.valid?'status-dot good':'status-dot'}>● {validation.valid?'READY':'DRAFT'}</span><span className="save-state">{saveState==='saved'?'Saved locally':saveState==='saving'?'Saving…':'Local save failed'}</span><button onClick={newPack}>New</button><button onClick={()=>setShowSheet(true)}>Preview pack</button></div></header>
  <section className="workspace">
   <aside className="sidebar"><p className="eyebrow">01 · GARMENT</p><div className="switch"><button className={category==='tshirt'?'active':''} onClick={()=>setCategory('tshirt')}>T-shirt</button><button className={category==='hoodie'?'active':''} onClick={()=>setCategory('hoodie')}>Hoodie</button></div><label>Style name<input value={styleName||spec.name} onChange={e=>setStyleName(e.target.value)} /></label><label>Fit<select value={fit} onChange={e=>setFit(e.target.value as Fit)}><option value="regular">Regular</option><option value="oversized">Oversized</option><option value="cropped">Cropped</option></select></label><label>Colorway<input value={colorway||spec.colorways[0]} onChange={e=>setColorway(e.target.value)} /></label>
    <button className={validation.valid?'validation valid':'validation invalid'} onClick={()=>setShowValidation(v=>!v)}>{validation.valid?'✓ Pack structure complete':`${validation.errors.length} critical issue${validation.errors.length===1?'':'s'}`} {validation.warnings.length?`· ${validation.warnings.length} warning${validation.warnings.length===1?'':'s'}`:''}</button>
    {showValidation&&!validation.valid&&<div className="validation-panel">{validation.errors.map(error=><button key={error} className="validation-item" onClick={()=>{setTab(validationTab(error));setShowValidation(false)}}>• {error}</button>)}{validation.warnings.map(warning=><div className="validation-warning" key={warning}>△ {warning}</div>)}</div>}
    <div className="sidebar-actions"><button className="export" disabled={hasCriticalErrors} onClick={exportPack}>Export SVG ↓</button><button className="print" disabled={hasCriticalErrors} onClick={printPack}>Print / Save PDF</button></div>
   </aside>
   <section className="canvas"><div className="canvas-head"><div><p className="eyebrow">02 · DESIGN WORKSPACE</p><h1>{spec.name}</h1><span className="workspace-meta">{spec.category==='hoodie'?'HOODIE':'T-SHIRT'} · {spec.fit.toUpperCase()} · {spec.colorways.join(', ')||'COLOR TBD'}</span></div><div className="tabs">{tabs.map(t=><button key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div></div>
    {tab==='flat'&&<div className="flat-stage"><div className="sheet-label">TECHNICAL FLAT · FRONT / BACK</div><div className="flat" dangerouslySetInnerHTML={{__html:preview.flatSvg}} /></div>}
    {tab==='measurements'&&<div className="editable-table"><div className="row header"><span>POM</span><span>Definition</span><span>Spec</span><span>Tolerance</span></div>{preview.pom.map(p=><div className="row" key={p.id}><span>{p.code}</span><span>{p.definition}</span><span><input type="number" value={p.value??''} placeholder="TBD" onChange={e=>{const value=Number(e.target.value);if(e.target.value==='')return setMeasurements(current=>{const next={...current};delete next[p.id];return next});if(Number.isFinite(value))setMeasurements(current=>({...current,[p.id]:value}))}}/> {p.unit}</span><span>{p.tolerance?`±${p.tolerance}`:'—'}</span></div>)}</div>}
    {tab==='bom'&&<div className="editable-table"><div className="row header"><span>Component</span><span>Specification</span><span>Placement</span></div>{preview.bom.map(b=><div className="row" key={b.id}><span>{b.item}</span><span><input value={b.specification} onChange={e=>setBomEdits(current=>({...current,[b.id]:{...current[b.id],specification:e.target.value}}))}/></span><span><input value={b.placement??''} placeholder="—" onChange={e=>setBomEdits(current=>({...current,[b.id]:{...current[b.id],placement:e.target.value}}))}/></span></div>)}</div>}
    {tab==='construction'&&<div className="editable-table"><div className="row header"><span>Operation</span><span>Seam</span><span>Stitch</span></div>{preview.construction.map(c=><div className="row" key={c.id}><span><input value={c.operation} onChange={e=>setConstructionEdits(current=>({...current,[c.id]:{...current[c.id],operation:e.target.value}}))}/></span><span><input value={c.seam??''} onChange={e=>setConstructionEdits(current=>({...current,[c.id]:{...current[c.id],seam:e.target.value}}))}/></span><span><input value={c.stitch??''} onChange={e=>setConstructionEdits(current=>({...current,[c.id]:{...current[c.id],stitch:e.target.value}}))}/></span></div>)}</div>}
    {tab==='artwork'&&<div className="artwork-list">{artworks.map((artwork,index)=><article className="artwork-card" key={artwork.id}><div className="artwork-card-head"><strong>{String(index+1).padStart(2,'0')} · {artwork.name}</strong>{artworks.length>1&&<button onClick={()=>removeArtwork(artwork.id)}>Remove</button>}</div><div className="placement-chip">{artworkPlacementLabels[artwork.placement]}</div><label>Artwork file<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&importArtwork(artwork.id,e.target.files[0])}/></label>{artwork.assetName&&<div className="asset-preview"><img src={artwork.assetDataUrl} alt={artwork.assetName}/><span>{artwork.assetName}</span></div>}<label>Artwork name<input value={artwork.name} onChange={e=>updateArtwork(artwork.id,'name',e.target.value)}/></label><label>Technique<select value={artwork.technique} onChange={e=>updateArtwork(artwork.id,'technique',e.target.value as ArtworkTechnique)}>{[['screen-print','Screen print'],['dtg','DTG'],['embroidery','Embroidery'],['heat-transfer','Heat transfer'],['applique','Appliqué'],['label','Label']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Placement<select value={artwork.placement} onChange={e=>updateArtwork(artwork.id,'placement',e.target.value as ArtworkPlacement)}>{Object.entries(artworkPlacementLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="two"><label>Width<input value={artwork.width} onChange={e=>updateArtwork(artwork.id,'width',e.target.value)}/></label><label>Height<input value={artwork.height} onChange={e=>updateArtwork(artwork.id,'height',e.target.value)}/></label></div><label>Colors<input value={artwork.colors} onChange={e=>updateArtwork(artwork.id,'colors',e.target.value)}/></label><label>Notes<textarea value={artwork.notes??''} onChange={e=>updateArtwork(artwork.id,'notes',e.target.value)}/></label></article>)}<button className="add-artwork" onClick={addArtwork}>+ Add artwork / print</button></div>}
   </section>
  </section>
  {showSheet&&<div className="modal" onClick={()=>setShowSheet(false)}><div className="pack-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><span>TECH PACK PREVIEW</span><div><button onClick={printPack} disabled={hasCriticalErrors}>Save PDF / Print</button><button onClick={()=>setShowSheet(false)}>Close</button></div></div><div className="pack-preview" dangerouslySetInnerHTML={{__html:preview.sheetSvg}} /><div className="modal-actions"><button className="download" disabled={hasCriticalErrors} onClick={exportPack}>Export SVG ↓</button></div></div></div>}
 </main>
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)
function downloadSvg(svg:string,filename:string){const blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
function openPrintWindow(svg:string,title:string){const printWindow=window.open('','_blank','noopener,noreferrer');if(!printWindow)return;printWindow.document.write(`<!doctype html><html><head><title>${escapeHtml(title)} · Tech Pack</title><style>@page{size:A4 portrait;margin:8mm}html,body{margin:0;background:#fff}body{font-family:Arial,sans-serif}svg{display:block;width:100%;height:auto} @media print{svg{break-inside:avoid}}</style></head><body>${svg}</body></html>`);printWindow.document.close();printWindow.focus();window.setTimeout(()=>printWindow.print(),250)}
function escapeHtml(value:string){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
